import { Amplify } from 'https://esm.sh/aws-amplify@6';
import {
  signIn,
  signUp,
  confirmSignUp,
  signOut as amplifySignOut,
  getCurrentUser,
  fetchAuthSession,
  signInWithRedirect,
  fetchUserAttributes,
} from 'https://esm.sh/aws-amplify@6/auth';
import { Hub } from 'https://esm.sh/aws-amplify@6/utils';

// Load Amplify outputs generated by 'npx ampx sandbox' or Amplify CI/CD
let configured = false;
async function ensureConfigured() {
  if (configured) return;
  try {
    const res = await fetch('/amplify_outputs.json');
    if (res.ok) {
      const outputs = await res.json();
      // Only configure if real values exist (not placeholder)
      if (outputs.auth && !outputs.auth.user_pool_id.startsWith('PLACEHOLDER')) {
        Amplify.configure(outputs);
        configured = true;
      }
    }
  } catch {
    // amplify_outputs.json not available — auth requires deployment
  }
}

await ensureConfigured();

// ── Social sign-in (redirect-based via Cognito hosted UI) ──────────────────
export async function signInWithGoogle() {
  await ensureConfigured();
  return signInWithRedirect({ provider: 'Google' });
}

export async function signInWithGitHub() {
  await ensureConfigured();
  // GitHub requires OIDC custom provider configured in Cognito console
  return signInWithRedirect({ provider: { custom: 'GitHub' } });
}

// ── Email / password ───────────────────────────────────────────────────────
export async function signInWithEmail(email, password) {
  await ensureConfigured();
  const result = await signIn({ username: email, password });
  return result;
}

export async function signUpWithEmail(email, password, displayName) {
  await ensureConfigured();
  const result = await signUp({
    username: email,
    password,
    options: {
      userAttributes: {
        email,
        name: displayName || '',
      },
    },
  });
  return result;
}

// ── Email verification (required after sign-up) ────────────────────────────
export async function confirmUserSignUp(email, code) {
  await ensureConfigured();
  return confirmSignUp({ username: email, confirmationCode: code });
}

// ── Sign out ───────────────────────────────────────────────────────────────
export async function signOut() {
  await ensureConfigured();
  return amplifySignOut();
}

// ── Normalized user profile ────────────────────────────────────────────────
async function buildUserProfile() {
  try {
    const user = await getCurrentUser();
    const attrs = await fetchUserAttributes().catch(() => ({}));
    return {
      username:    user.username,
      email:       attrs.email       || user.username,
      displayName: attrs.name        || attrs.email?.split('@')[0] || user.username,
      photoURL:    attrs.picture     || null,
    };
  } catch {
    return null;
  }
}

// ── Auth state observer (drop-in replacement for Firebase onAuthStateChanged)
export function onAuthChange(callback) {
  // Emit the current state immediately
  buildUserProfile().then(callback);

  // Listen for subsequent auth transitions
  Hub.listen('auth', async ({ payload }) => {
    const { event } = payload;
    if (['signedIn', 'tokenRefresh', 'signInWithRedirect'].includes(event)) {
      buildUserProfile().then(callback);
    } else if (event === 'signedOut' || event === 'signInWithRedirect_failure') {
      callback(null);
    }
  });
}

// ── Token for Ani chat identity injection ─────────────────────────────────
export async function getIdToken() {
  try {
    await ensureConfigured();
    const session = await fetchAuthSession();
    return session.tokens?.idToken?.toString() || null;
  } catch {
    return null;
  }
}
